[package]
name = "bitbucket-api"
version = "0.1.0"
authors = ["Benjamin Groeber"]
license = "MIT"

[dependencies]
curl = "0.4.18"
serde_derive = "1.0.80"
serde_json = "1.0.32"
serde = "1.0.80"
url = "1.7.1"
lazy_static = "1.1.0"
log = "0.4.5"
env_logger = "0.5.13"
